=== Benjamincro4/Autofarm/l2fidas - server/game/data/xsd/multisell.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="ingredient" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="isTaxIngredient" type="xs:boolean" />
									<xs:attribute name="maintainIngredient" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="production" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="applyTaxes" type="xs:boolean" />
			<xs:attribute name="maintainEnchantment" type="xs:boolean" />
			<xs:attribute name="useRate" type="xs:token" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Benjamincro4/Autofarm/l2fidas - server/game/data/multisell/364890001.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Schuttgart Human Mercenary -->
		<production count="1" id="13665" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Schuttgart Elf Mercenary -->
		<production count="1" id="13666" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Schuttgart Dark Elf Mercenary -->
		<production count="1" id="13667" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Schuttgart Orc Mercenary -->
		<production count="1" id="13668" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Schuttgart Dwarf Mercenary -->
		<production count="1" id="13669" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Schuttgart Kamael Mercenary -->
		<production count="1" id="13670" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="70000" id="57" />
		<!-- Schuttgart Disguise Scroll -->
		<production count="1" id="13685" />
	</item>
</list>

=== Benjamincro4/Autofarm/l2fidas - server/game/data/multisell/90001004.xml
<?xml version="1.0" encoding="UTF-8"?>
<list maintainEnchantment="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<item>
		<!-- Silk Shirt -->
		<ingredient count="1" id="9579" />
		<!-- Knight's Epaulette -->
		<ingredient count="120" id="9912" />
		<!-- Silk Shirt - HP -->
		<production count="1" id="10491" />
	</item>
	<item>
		<!-- Silk Shirt -->
		<ingredient count="1" id="9579" />
		<!-- Knight's Epaulette -->
		<ingredient count="120" id="9912" />
		<!-- Silk Shirt - MP -->
		<production count="1" id="10492" />
	</item>
	<item>
		<!-- Silk Shirt -->
		<ingredient count="1" id="9579" />
		<!-- Knight's Epaulette -->
		<ingredient count="60" id="9912" />
		<!-- Silk Shirt - CP -->
		<production count="1" id="10493" />
	</item>
	<item>
		<!-- Thin Leather Shirt -->
		<ingredient count="1" id="9580" />
		<!-- Knight's Epaulette -->
		<ingredient count="180" id="9912" />
		<!-- Thin Leather Shirt - HP -->
		<production count="1" id="10494" />
	</item>
	<item>
		<!-- Thin Leather Shirt -->
		<ingredient count="1" id="9580" />
		<!-- Knight's Epaulette -->
		<ingredient count="180" id="9912" />
		<!-- Thin Leather Shirt - MP -->
		<production count="1" id="10495" />
	</item>
	<item>
		<!-- Thin Leather Shirt -->
		<ingredient count="1" id="9580" />
		<!-- Knight's Epaulette -->
		<ingredient count="90" id="9912" />
		<!-- Thin Leather Shirt - CP -->
		<production count="1" id="10496" />
	</item>
	<item>
		<!-- Scale Shirt -->
		<ingredient count="1" id="9581" />
		<!-- Knight's Epaulette -->
		<ingredient count="240" id="9912" />
		<!-- Scale Shirt - HP -->
		<production count="1" id="10497" />
	</item>
	<item>
		<!-- Scale Shirt -->
		<ingredient count="1" id="9581" />
		<!-- Knight's Epaulette -->
		<ingredient count="240" id="9912" />
		<!-- Scale Shirt - MP -->
		<production count="1" id="10498" />
	</item>
	<item>
		<!-- Scale Shirt -->
		<ingredient count="1" id="9581" />
		<!-- Knight's Epaulette -->
		<ingredient count="120" id="9912" />
		<!-- Scale Shirt - CP -->
		<production count="1" id="10499" />
	</item>
	<item>
		<!-- Mithril Shirt -->
		<ingredient count="1" id="9582" />
		<!-- Knight's Epaulette -->
		<ingredient count="500" id="9912" />
		<!-- Mithril Shirt - HP -->
		<production count="1" id="10500" />
	</item>
	<item>
		<!-- Mithril Shirt -->
		<ingredient count="1" id="9582" />
		<!-- Knight's Epaulette -->
		<ingredient count="500" id="9912" />
		<!-- Mithril Shirt - MP -->
		<production count="1" id="10501" />
	</item>
	<item>
		<!-- Mithril Shirt -->
		<ingredient count="1" id="9582" />
		<!-- Knight's Epaulette -->
		<ingredient count="250" id="9912" />
		<!-- Mithril Shirt - CP -->
		<production count="1" id="10502" />
	</item>
	<item>
		<!-- Striped Silk Shirt -->
		<ingredient count="1" id="9585" />
		<!-- Knight's Epaulette -->
		<ingredient count="140" id="9912" />
		<!-- Striped Silk Shirt - HP -->
		<production count="1" id="10503" />
	</item>
	<item>
		<!-- Striped Silk Shirt -->
		<ingredient count="1" id="9585" />
		<!-- Knight's Epaulette -->
		<ingredient count="140" id="9912" />
		<!-- Striped Silk Shirt - MP -->
		<production count="1" id="10504" />
	</item>
	<item>
		<!-- Striped Silk Shirt -->
		<ingredient count="1" id="9585" />
		<!-- Knight's Epaulette -->
		<ingredient count="70" id="9912" />
		<!-- Striped Silk Shirt - CP -->
		<production count="1" id="10505" />
	</item>
	<item>
		<!-- Thin Striped Leather Shirt -->
		<ingredient count="1" id="9586" />
		<!-- Knight's Epaulette -->
		<ingredient count="210" id="9912" />
		<!-- Thin Striped Leather Shirt - HP -->
		<production count="1" id="10506" />
	</item>
	<item>
		<!-- Thin Striped Leather Shirt -->
		<ingredient count="1" id="9586" />
		<!-- Knight's Epaulette -->
		<ingredient count="210" id="9912" />
		<!-- Thin Striped Leather Shirt - MP -->
		<production count="1" id="10507" />
	</item>
	<item>
		<!-- Thin Striped Leather Shirt -->
		<ingredient count="1" id="9586" />
		<!-- Knight's Epaulette -->
		<ingredient count="105" id="9912" />
		<!-- Thin Striped Leather Shirt - CP -->
		<production count="1" id="10508" />
	</item>
	<item>
		<!-- Striped Scale Shirt -->
		<ingredient count="1" id="9587" />
		<!-- Knight's Epaulette -->
		<ingredient count="310" id="9912" />
		<!-- Striped Scale Shirt - HP -->
		<production count="1" id="10509" />
	</item>
	<item>
		<!-- Striped Scale Shirt -->
		<ingredient count="1" id="9587" />
		<!-- Knight's Epaulette -->
		<ingredient count="310" id="9912" />
		<!-- Striped Scale Shirt - MP -->
		<production count="1" id="10510" />
	</item>
	<item>
		<!-- Striped Scale Shirt -->
		<ingredient count="1" id="9587" />
		<!-- Knight's Epaulette -->
		<ingredient count="155" id="9912" />
		<!-- Striped Scale Shirt - CP -->
		<production count="1" id="10511" />
	</item>
	<item>
		<!-- Striped Mithril Shirt -->
		<ingredient count="1" id="9588" />
		<!-- Knight's Epaulette -->
		<ingredient count="550" id="9912" />
		<!-- Striped Mithril Shirt - HP -->
		<production count="1" id="10512" />
	</item>
	<item>
		<!-- Striped Mithril Shirt -->
		<ingredient count="1" id="9588" />
		<!-- Knight's Epaulette -->
		<ingredient count="550" id="9912" />
		<!-- Striped Mithril Shirt - MP -->
		<production count="1" id="10513" />
	</item>
	<item>
		<!-- Striped Mithril Shirt -->
		<ingredient count="1" id="9588" />
		<!-- Knight's Epaulette -->
		<ingredient count="225" id="9912" />
		<!-- Striped Mithril Shirt - CP -->
		<production count="1" id="10514" />
	</item>
</list>
